import Header from "../components/Header";
import Head from "next/head";

export default function ContactMe() {
  return (
    <div>
      <Head>
        <title>Contact Me - Nicholas Lane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}
