import Head from "next/head";
import Header from "../components/Header";
import IntroSection from "../components/IntroSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nicholas Lane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <IntroSection />
      {/* <div className="h-32 w-32">
        <footer className="absolute inset-x-0 bottom-0 h-16">
          <div className="text-gray-700 text-center p-4 bg-gray-300">
            Nicholas Lane - 2022
          </div>
        </footer>
      </div> */}
    </div>
  );
}
